import { Service } from "@/entities/service/model";

export const mockServices: Service[] = [
  // ====== Салон ======
  {
    id: "salon_1",
    title: "Мойка салона",
    short_description: "Полная мойка салона",
    long_description:
      "Комплексная чистка всех поверхностей салона, включая пылесос и обработку пластика",
    category: "salon",
    duration_minutes: 30,
    popular: true,
    result_descriptions: [
      "Салон чистый и свежий",
      "Удалены пятна и пыль",
      "Повышенная защита от загрязнений",
    ],
    tags: ["~30 мин"],
    prices: { sedan: 450, crossover: 550, minivan: 650, carpet: 0 },
  },
  {
    id: "salon_2",
    title: "Пылесос",
    short_description: "Вакуумная чистка салона",
    long_description: "Удаление пыли и мелкого мусора с ковров, сидений и пола",
    category: "salon",
    duration_minutes: 20,
    popular: true,
    result_descriptions: [
      "Ковры чистые",
      "Сидения без пыли",
      "Свежий запах в салоне",
    ],
    tags: ["~20 мин"],
    prices: { sedan: 200, crossover: 250, minivan: 300, carpet: 0 },
  },
  {
    id: "salon_3",
    title: "Восстановитель пластика",
    short_description: "Обновление пластиковых деталей",
    long_description:
      "Средство для восстановления цвета и защиты пластика салона",
    category: "salon",
    duration_minutes: 25,
    popular: false,
    result_descriptions: [
      "Пластик выглядит «как новый»",
      "Защита от ультрафиолета",
      "Повышенная стойкость к пыли и мелким повреждениям",
    ],
    tags: ["~25 мин"],
    prices: { sedan: 300, crossover: 300, minivan: 350, carpet: 0 },
  },
  {
    id: "salon_4",
    title: "Мойка ковриков",
    short_description: "Очистка всех ковриков",
    long_description: "Глубокая очистка ковровых покрытий салона и багажника",
    category: "salon",
    duration_minutes: 15,
    popular: false,
    result_descriptions: [
      "Коврики чистые и сухие",
      "Удалены пыль и мелкий мусор",
    ],
    tags: ["~15 мин"],
    prices: { sedan: 100, crossover: 100, minivan: 100, carpet: 0 },
  },
  {
    id: "salon_5",
    title: "Кондиционер кожи",
    short_description: "Обработка кожаных поверхностей",
    long_description: "Кондиционирование и защита кожи салона",
    category: "salon",
    duration_minutes: 30,
    popular: true,
    result_descriptions: [
      "Кожа мягкая и эластичная",
      "Защита от трещин и выцветания",
      "Свежий вид салона",
    ],
    tags: ["~30 мин"],
    prices: { sedan: 450, crossover: 550, minivan: 650, carpet: 0 },
  },
  {
    id: "salon_6",
    title: "Полироль пластика",
    short_description: "Полировка пластиковых деталей",
    long_description:
      "Удаление мелких царапин и восстановление блеска пластика",
    category: "salon",
    duration_minutes: 20,
    popular: false,
    result_descriptions: [
      "Пластик блестящий",
      "Защита от пыли",
      "Выглядит как новый",
    ],
    tags: ["~20 мин"],
    prices: { sedan: 300, crossover: 350, minivan: 400, carpet: 0 },
  },
  {
    id: "salon_7",
    title: "Багажник",
    short_description: "Чистка багажника",
    long_description: "Очистка багажника от пыли, мусора и пятен",
    category: "salon",
    duration_minutes: 15,
    popular: false,
    result_descriptions: ["Багажник чистый и сухой", "Удалены пятна и пыль"],
    tags: ["~15 мин"],
    prices: { sedan: 150, crossover: 200, minivan: 250, carpet: 0 },
  },

  // ====== Кузов ======
  {
    id: "body_1",
    title: "Кузов (с пеной с протиркой)",
    short_description: "Мойка кузова с обработкой пеной",
    long_description:
      "Очистка кузова с применением пены и протиркой всех поверхностей",
    category: "body",
    duration_minutes: 30,
    popular: true,
    result_descriptions: [
      "Чистый кузов без пятен",
      "Удалены загрязнения и пыль",
      "Поверхность готова к полировке",
    ],
    tags: ["~30 мин"],
    prices: { sedan: 450, crossover: 550, minivan: 650, carpet: 0 },
  },
  {
    id: "body_2",
    title: "Отбивка (с пеной без протирки)",
    short_description: "Мойка кузова без протирки",
    long_description: "Обработка кузова пеной без последующей протирки",
    category: "body",
    duration_minutes: 25,
    popular: false,
    result_descriptions: ["Чистый кузов", "Удалены крупные загрязнения"],
    tags: ["~25 мин"],
    prices: { sedan: 400, crossover: 450, minivan: 600, carpet: 0 },
  },
  {
    id: "body_3",
    title: "Удаление мошек",
    short_description: "Очистка кузова от насекомых",
    long_description: "Удаление следов насекомых и загрязнений с кузова",
    category: "body",
    duration_minutes: 15,
    popular: false,
    result_descriptions: [
      "Кузов без следов насекомых",
      "Поверхность гладкая и чистая",
    ],
    tags: ["~15 мин"],
    prices: { sedan: 100, crossover: 100, minivan: 100, carpet: 0 },
  },
  {
    id: "body_4",
    title: "Удаление битумных пятен",
    short_description: "Чистка битумных следов",
    long_description: "Удаление битумных пятен с кузова автомобиля",
    category: "body",
    duration_minutes: 20,
    popular: false,
    result_descriptions: ["Кузов чистый, без битума", "Поверхность ровная"],
    tags: ["~20 мин"],
    prices: { sedan: 250, crossover: 250, minivan: 250, carpet: 0 },
  },
  {
    id: "body_5",
    title: "Восстановитель пластика",
    short_description: "Обновление пластиковых деталей кузова",
    long_description: "Обновление цвета и защита пластиковых частей кузова",
    category: "body",
    duration_minutes: 25,
    popular: false,
    result_descriptions: [
      "Пластик выглядит как новый",
      "Защита от ультрафиолета",
    ],
    tags: ["~25 мин"],
    prices: { sedan: 250, crossover: 300, minivan: 350, carpet: 0 },
  },
  {
    id: "body_6",
    title: "Чернение резины",
    short_description: "Обработка резины на колесах",
    long_description: "Чернение и защита резиновых элементов автомобиля",
    category: "body",
    duration_minutes: 15,
    popular: false,
    result_descriptions: ["Резина выглядит новой", "Защита от трещин"],
    tags: ["~15 мин"],
    prices: { sedan: 100, crossover: 100, minivan: 100, carpet: 0 },
  },
  {
    id: "body_7",
    title: "Очистка дисков",
    short_description: "Чистка колесных дисков",
    long_description: "Удаление грязи и пыли с колесных дисков",
    category: "body",
    duration_minutes: 20,
    popular: false,
    result_descriptions: ["Диски чистые и блестящие"],
    tags: ["~20 мин"],
    prices: { sedan: 250, crossover: 250, minivan: 250, carpet: 0 },
  },
  {
    id: "body_8",
    title: "Воск",
    short_description: "Нанесение воска на кузов",
    long_description: "Защита кузова и придание блеска",
    category: "body",
    duration_minutes: 30,
    popular: true,
    result_descriptions: ["Блеск кузова", "Защита от влаги и пыли"],
    tags: ["~30 мин"],
    prices: { sedan: 250, crossover: 300, minivan: 350, carpet: 0 },
  },
  {
    id: "body_9",
    title: "Кварцевое покрытие",
    short_description: "Нанесение кварцевого покрытия",
    long_description: "Долговременная защита кузова с блеском",
    category: "body",
    duration_minutes: 45,
    popular: true,
    result_descriptions: [
      "Защита кузова до 6 месяцев",
      "Блеск и стойкость к мелким повреждениям",
    ],
    tags: ["~45 мин"],
    prices: { sedan: 500, crossover: 700, minivan: 900, carpet: 0 },
  },
  {
    id: "body_10",
    title: "Жидкий полимер",
    short_description: "Защитное покрытие кузова",
    long_description: "Прозрачная защита кузова от внешних факторов",
    category: "body",
    duration_minutes: 60,
    popular: true,
    result_descriptions: [
      "Защита от ультрафиолета и грязи",
      "Легкая очистка кузова",
    ],
    tags: ["~60 мин"],
    prices: { sedan: 1000, crossover: 1250, minivan: 1500, carpet: 0 },
  },
  {
    id: "body_11",
    title: "Твёрдый воск",
    short_description: "Нанесение твёрдого воска",
    long_description: "Защитное покрытие кузова с блеском и стойкостью",
    category: "body",
    duration_minutes: 60,
    popular: false,
    result_descriptions: ["Блеск и защита кузова", "Долговременная стойкость"],
    tags: ["~60 мин"],
    prices: { sedan: 1500, crossover: 2000, minivan: 2500, carpet: 0 },
  },

  // ====== Химчистка ======
  {
    id: "dryclean_1",
    title: "Химчистка салона",
    short_description: "Глубокая химчистка салона",
    long_description: "Полная химчистка салона с обработкой всех поверхностей",
    category: "dryclean",
    duration_minutes: 120,
    popular: true,
    result_descriptions: [
      "Салон без пятен и запаха",
      "Материалы обновлены и защищены",
    ],
    tags: ["~2 ч"],
    prices: { sedan: 9000, crossover: 10000, minivan: 11000, carpet: 0 },
  },
  {
    id: "dryclean_2",
    title: "Химчистка торпеды и стоек",
    short_description: "Обработка панели и стоек",
    long_description: "Удаление загрязнений и пятен с панели и стоек",
    category: "dryclean",
    duration_minutes: 30,
    popular: false,
    result_descriptions: ["Панель чистая и свежая", "Материалы защищены"],
    tags: ["~30 мин"],
    prices: { sedan: 1500, crossover: 1500, minivan: 1500, carpet: 0 },
  },
  {
    id: "dryclean_3",
    title: "Химчистка одного сидения",
    short_description: "Чистка одного сидения",
    long_description: "Глубокая чистка одного сидения салона",
    category: "dryclean",
    duration_minutes: 20,
    popular: false,
    result_descriptions: ["Сидение чистое и сухое", "Удалены пятна и запахи"],
    tags: ["~20 мин"],
    prices: { sedan: 800, crossover: 800, minivan: 800, carpet: 0 },
  },
  {
    id: "dryclean_4",
    title: "Химчистка одной двери",
    short_description: "Чистка дверной панели",
    long_description: "Глубокая очистка дверной панели и внутренней обшивки",
    category: "dryclean",
    duration_minutes: 15,
    popular: false,
    result_descriptions: ["Дверь чистая", "Материалы обновлены"],
    tags: ["~15 мин"],
    prices: { sedan: 300, crossover: 300, minivan: 300, carpet: 0 },
  },
  {
    id: "dryclean_5",
    title: "Химчистка ковролина",
    short_description: "Чистка ковровых покрытий",
    long_description: "Глубокая очистка ковролина в салоне и багажнике",
    category: "dryclean",
    duration_minutes: 60,
    popular: true,
    result_descriptions: ["Ковролин чистый", "Удалены пятна и запахи"],
    tags: ["~1 ч"],
    prices: { sedan: 2500, crossover: 2500, minivan: 2500, carpet: 1200 },
  },
  {
    id: "dryclean_6",
    title: "Химчистка багажника",
    short_description: "Очистка багажника",
    long_description: "Удаление грязи и пятен из багажника",
    category: "dryclean",
    duration_minutes: 45,
    popular: false,
    result_descriptions: ["Багажник чистый", "Удалены пятна и запахи"],
    tags: ["~45 мин"],
    prices: { sedan: 2000, crossover: 2000, minivan: 2000, carpet: 1200 },
  },
  {
    id: "dryclean_7",
    title: "Химчистка потолка",
    short_description: "Очистка потолочного покрытия",
    long_description: "Удаление загрязнений и пятен с потолка салона",
    category: "dryclean",
    duration_minutes: 60,
    popular: false,
    result_descriptions: ["Потолок чистый и свежий", "Материалы обновлены"],
    tags: ["~1 ч"],
    prices: { sedan: 2500, crossover: 2500, minivan: 2500, carpet: 1200 },
  },
  {
    id: "dryclean_8",
    title: "Химчистка детских кресел и колясок",
    short_description: "Чистка детских кресел и колясок",
    long_description: "Удаление пятен и запахов с детских кресел и колясок",
    category: "dryclean",
    duration_minutes: 30,
    popular: false,
    result_descriptions: [
      "Кресло чистое и безопасное",
      "Удалены запахи и пятна",
    ],
    tags: ["~30 мин"],
    prices: { sedan: 1000, crossover: 1000, minivan: 1000, carpet: 0 },
  },
];
