import { ObjectType } from "@/entities/booking/model";
import { Service } from "@/entities/service/model";

export const CATEGORY_GROUPS: Record<
  ObjectType,
  { name: string; value: Service["category"] }[]
> = {
  sedan: [
    { name: "Салон", value: "salon" },
    { name: "Кузов", value: "body" },
    { name: "Химчистка", value: "dryclean" },
  ],
  crossover: [
    { name: "Салон", value: "salon" },
    { name: "Кузов", value: "body" },
    { name: "Химчистка", value: "dryclean" },
  ],
  minivan: [
    { name: "Салон", value: "salon" },
    { name: "Кузов", value: "body" },
    { name: "Химчистка", value: "dryclean" },
  ],
  special: [{ name: "Специальные", value: "special" }],
};

export const ALL_CATEGORIES = [
  { name: "Салон", value: "salon" },
  { name: "Кузов", value: "body" },
  { name: "Химчистка", value: "dryclean" },
  { name: "Специальные", value: "special" },
];

export const mockServices: Service[] = [
  // ====== Салон ======
  {
    id: "salon_1",
    title: "Мойка салона",
    shortDescription: "Полная мойка салона",
    longDescription:
      "Комплексная чистка всех поверхностей салона, включая пылесос и обработку пластика",
    category: "salon",
    popular: true,
    resultDescriptions: [
      "Салон чистый и свежий",
      "Удалены пятна и пыль",
      "Повышенная защита от загрязнений",
    ],
    tags: ["~30 мин"],
    prices: { sedan: 450, crossover: 550, minivan: 650 },
    duration: { sedan: 30, crossover: 30, minivan: 30 },
    objectTypes: ["sedan", "crossover", "minivan"],
    mainImage: "",
    additionalImages: [],
    subServiceIds: ["salon_2", "salon_4", "glasses_1"],
    parentServiceId: "dryclean_1",
  },
  {
    id: "glasses_1",
    title: "Мойка стекол",
    shortDescription: "Моем стекла",
    longDescription: "Моем стекла",
    category: "salon",
    popular: true,
    resultDescriptions: ["стекла чистые и свежие"],
    tags: ["~10 мин"],
    prices: { sedan: 200, crossover: 200, minivan: 200 },
    duration: { sedan: 10, crossover: 10, minivan: 10 },
    objectTypes: ["sedan", "crossover", "minivan"],
    mainImage: "",
    additionalImages: [],
    parentServiceId: "dryclean_1",
  },
  {
    id: "salon_2",
    title: "Пылесос",
    shortDescription: "Вакуумная чистка салона",
    longDescription: "Удаление пыли и мелкого мусора с ковров, сидений и пола",
    category: "salon",
    popular: true,
    resultDescriptions: [
      "Ковры чистые",
      "Сидения без пыли",
      "Свежий запах в салоне",
    ],
    tags: ["~20 мин"],
    prices: { sedan: 200, crossover: 250, minivan: 300 },
    duration: { sedan: 20, crossover: 20, minivan: 20 },
    objectTypes: ["sedan", "crossover", "minivan"],
    mainImage: "",
    additionalImages: [],
    subServiceIds: [],
    parentServiceId: "salon_1",
  },
  {
    id: "salon_3",
    title: "Восстановитель пластика",
    shortDescription: "Обновление пластиковых деталей",
    longDescription:
      "Средство для восстановления цвета и защиты пластика салона",
    category: "salon",
    popular: false,
    resultDescriptions: [
      "Пластик выглядит «как новый»",
      "Защита от ультрафиолета",
      "Повышенная стойкость к пыли и мелким повреждениям",
    ],
    tags: ["~25 мин"],
    prices: { sedan: 300, crossover: 300, minivan: 350 },
    duration: { sedan: 25, crossover: 25, minivan: 25 },
    objectTypes: ["sedan", "crossover", "minivan"],
    mainImage: "",
    additionalImages: [],
  },
  {
    id: "salon_4",
    title: "Мойка ковриков",
    shortDescription: "Очистка всех ковриков",
    longDescription: "Глубокая очистка ковровых покрытий салона",
    category: "salon",
    popular: false,
    resultDescriptions: [
      "Коврики чистые и сухие",
      "Удалены пыль и мелкий мусор",
    ],
    tags: ["~15 мин"],
    prices: { sedan: 100, crossover: 100, minivan: 100 },
    duration: { sedan: 15, crossover: 15, minivan: 15 },
    objectTypes: ["sedan", "crossover", "minivan"],
    mainImage: "",
    additionalImages: [],
    parentServiceId: "salon_1",
  },
  {
    id: "salon_5",
    title: "Кондиционер кожи",
    shortDescription: "Обработка кожаных поверхностей",
    longDescription: "Кондиционирование и защита кожи салона",
    category: "salon",
    popular: true,
    resultDescriptions: [
      "Кожа мягкая и эластичная",
      "Защита от трещин и выцветания",
      "Свежий вид салона",
    ],
    tags: ["~30 мин"],
    prices: { sedan: 450, crossover: 550, minivan: 650 },
    duration: { sedan: 30, crossover: 30, minivan: 30 },
    objectTypes: ["sedan", "crossover", "minivan"],
    mainImage: "",
    additionalImages: [],
  },
  {
    id: "salon_6",
    title: "Полироль пластика",
    shortDescription: "Полировка пластиковых деталей",
    longDescription: "Удаление мелких царапин и восстановление блеска пластика",
    category: "salon",
    popular: false,
    resultDescriptions: [
      "Пластик блестящий",
      "Защита от пыли",
      "Выглядит как новый",
    ],
    tags: ["~20 мин"],
    prices: { sedan: 300, crossover: 350, minivan: 400 },
    duration: { sedan: 20, crossover: 20, minivan: 20 },
    objectTypes: ["sedan", "crossover", "minivan"],
    mainImage: "",
    additionalImages: [],
    subServiceIds: [],
  },
  {
    id: "salon_7",
    title: "Багажник",
    shortDescription: "Чистка багажника",
    longDescription: "Очистка багажника от пыли, мусора и пятен",
    category: "salon",
    popular: false,
    resultDescriptions: ["Багажник чистый и сухой", "Удалены пятна и пыль"],
    tags: ["~15 мин"],
    prices: { sedan: 150, crossover: 200, minivan: 250 },
    duration: { sedan: 15, crossover: 15, minivan: 15 },
    objectTypes: ["sedan", "crossover", "minivan"],
    mainImage: "",
    additionalImages: [],
    subServiceIds: [],
    parentServiceId: "dryclean_6",
  },

  // ====== Кузов ======
  {
    id: "body_1",
    title: "Кузов (с пеной с протиркой)",
    shortDescription: "Мойка кузова с обработкой пеной",
    longDescription:
      "Очистка кузова с применением пены и протиркой всех поверхностей",
    category: "body",
    popular: true,
    resultDescriptions: [
      "Чистый кузов без пятен",
      "Удалены загрязнения и пыль",
      "Поверхность готова к полировке",
    ],
    tags: ["~30 мин"],
    prices: { sedan: 450, crossover: 550, minivan: 650 },
    duration: { sedan: 30, crossover: 30, minivan: 30 },
    objectTypes: ["sedan", "crossover", "minivan"],
    mainImage: "",
    additionalImages: [],
    subServiceIds: ["body_2"],
  },
  {
    id: "body_2",
    title: "Отбивка (с пеной без протирки)",
    shortDescription: "Мойка кузова без протирки",
    longDescription: "Обработка кузова пеной без последующей протирки",
    category: "body",
    popular: false,
    resultDescriptions: ["Чистый кузов", "Удалены крупные загрязнения"],
    tags: ["~25 мин"],
    prices: { sedan: 400, crossover: 450, minivan: 600 },
    duration: { sedan: 25, crossover: 25, minivan: 25 },
    objectTypes: ["sedan", "crossover", "minivan"],
    mainImage: "",
    additionalImages: [],
    subServiceIds: [],
  },
  {
    id: "body_3",
    title: "Удаление мошек",
    shortDescription: "Очистка кузова от насекомых",
    longDescription: "Удаление следов насекомых и загрязнений с кузова",
    category: "body",
    popular: false,
    resultDescriptions: [
      "Кузов без следов насекомых",
      "Поверхность гладкая и чистая",
    ],
    tags: ["~15 мин"],
    prices: { sedan: 100, crossover: 100, minivan: 100 },
    duration: { sedan: 15, crossover: 15, minivan: 15 },
    objectTypes: ["sedan", "crossover", "minivan"],
    mainImage: "",
    additionalImages: [],
    subServiceIds: [],
  },
  {
    id: "body_4",
    title: "Удаление битумных пятен",
    shortDescription: "Чистка битумных следов",
    longDescription: "Удаление битумных пятен с кузова автомобиля",
    category: "body",
    popular: false,
    resultDescriptions: ["Кузов чистый, без битума", "Поверхность ровная"],
    tags: ["~20 мин"],
    prices: { sedan: 250, crossover: 250, minivan: 250 },
    duration: { sedan: 20, crossover: 20, minivan: 20 },
    objectTypes: ["sedan", "crossover", "minivan"],
    mainImage: "",
    additionalImages: [],
    subServiceIds: [],
    measure: "деталь",
  },
  {
    id: "body_5",
    title: "Восстановитель пластика",
    shortDescription: "Обновление пластиковых деталей кузова",
    longDescription: "Обновление цвета и защита пластиковых частей кузова",
    category: "body",
    popular: false,
    resultDescriptions: [
      "Пластик выглядит как новый",
      "Защита от ультрафиолета",
    ],
    tags: ["~25 мин"],
    prices: { sedan: 250, crossover: 300, minivan: 350 },
    duration: { sedan: 25, crossover: 25, minivan: 25 },
    objectTypes: ["sedan", "crossover", "minivan"],
    mainImage: "",
    additionalImages: [],
    subServiceIds: [],
  },
  {
    id: "body_6",
    title: "Чернение резины",
    shortDescription: "Обработка резины на колесах",
    longDescription: "Чернение и защита резиновых элементов автомобиля",
    category: "body",
    popular: false,
    resultDescriptions: ["Резина выглядит новой", "Защита от трещин"],
    tags: ["~15 мин"],
    prices: { sedan: 100, crossover: 100, minivan: 100 },
    duration: { sedan: 15, crossover: 15, minivan: 15 },
    objectTypes: ["sedan", "crossover", "minivan"],
    mainImage: "",
    additionalImages: [],
    subServiceIds: [],
  },
  {
    id: "body_7",
    title: "Очистка дисков",
    shortDescription: "Чистка колесных дисков",
    longDescription: "Удаление грязи и пыли с колесных дисков",
    category: "body",
    popular: false,
    resultDescriptions: ["Диски чистые и блестящие"],
    tags: ["~20 мин"],
    prices: { sedan: 250, crossover: 250, minivan: 250 },
    duration: { sedan: 20, crossover: 20, minivan: 20 },
    objectTypes: ["sedan", "crossover", "minivan"],
    mainImage: "",
    additionalImages: [],
    subServiceIds: [],
  },
  {
    id: "body_8",
    title: "Воск",
    shortDescription: "Нанесение воска на кузов",
    longDescription: "Защита кузова и придание блеска",
    category: "body",
    popular: true,
    resultDescriptions: ["Блеск кузова", "Защита от влаги и пыли"],
    tags: ["~30 мин"],
    prices: { sedan: 250, crossover: 300, minivan: 350 },
    duration: { sedan: 30, crossover: 30, minivan: 30 },
    objectTypes: ["sedan", "crossover", "minivan"],
    mainImage: "",
    additionalImages: [],
    subServiceIds: ["body_9", "body_10", "body_11"],
  },
  {
    id: "body_9",
    title: "Кварцевое покрытие",
    shortDescription: "Нанесение кварцевого покрытия",
    longDescription: "Долговременная защита кузова с блеском",
    category: "body",
    popular: true,
    resultDescriptions: [
      "Защита кузова до 6 месяцев",
      "Блеск и стойкость к мелким повреждениям",
    ],
    tags: ["~45 мин"],
    prices: { sedan: 500, crossover: 700, minivan: 900 },
    duration: { sedan: 45, crossover: 45, minivan: 45 },
    objectTypes: ["sedan", "crossover", "minivan"],
    mainImage: "",
    additionalImages: [],
    subServiceIds: ["body_8", "body_10", "body_11"],
  },
  {
    id: "body_10",
    title: "Жидкий полимер",
    shortDescription: "Защитное покрытие кузова",
    longDescription: "Прозрачная защита кузова от внешних факторов",
    category: "body",
    popular: true,
    resultDescriptions: [
      "Защита от ультрафиолета и грязи",
      "Легкая очистка кузова",
    ],
    tags: ["~60 мин"],
    prices: { sedan: 1000, crossover: 1250, minivan: 1500 },
    duration: { sedan: 60, crossover: 60, minivan: 60 },
    objectTypes: ["sedan", "crossover", "minivan"],
    mainImage: "",
    additionalImages: [],
    subServiceIds: ["body_8", "body_9", "body_11"],
  },
  {
    id: "body_11",
    title: "Твёрдый воск",
    shortDescription: "Нанесение твёрдого воска",
    longDescription: "Защитное покрытие кузова с блеском и стойкостью",
    category: "body",
    popular: false,
    resultDescriptions: ["Блеск и защита кузова", "Долговременная стойкость"],
    tags: ["~60 мин"],
    prices: { sedan: 1500, crossover: 2000, minivan: 2500 },
    duration: { sedan: 60, crossover: 60, minivan: 60 },
    objectTypes: ["sedan", "crossover", "minivan"],
    mainImage: "",
    additionalImages: [],
    subServiceIds: ["body_8", "body_9", "body_10"],
  },
  {
    id: "body_12",
    title: "Обдув",
    shortDescription: "Обдув",
    longDescription: "Обдуваем",
    category: "body",
    popular: false,
    resultDescriptions: ["Обдув", "Обдув"],
    tags: ["~60 мин"],
    prices: { sedan: 100, crossover: 150, minivan: 200 },
    duration: { sedan: 10, crossover: 10, minivan: 10 },
    objectTypes: ["sedan", "crossover", "minivan"],
    mainImage: "",
    additionalImages: [],
  },

  // ====== Химчистка ======
  {
    id: "dryclean_1",
    title: "Химчистка салона",
    shortDescription: "Глубокая химчистка салона",
    longDescription: "Полная химчистка салона с обработкой всех поверхностей",
    category: "dryclean",
    popular: true,
    resultDescriptions: [
      "Салон без пятен и запаха",
      "Материалы обновлены и защищены",
    ],
    tags: ["~2 ч"],
    prices: { sedan: 9000, crossover: 10000, minivan: 11000 },
    duration: { sedan: 120, crossover: 120, minivan: 120 },
    objectTypes: ["sedan", "crossover", "minivan"],
    mainImage: "",
    additionalImages: [],
    subServiceIds: [
      "salon_1",
      "salon_2",
      "salon_4",
      "glasses_1",
      "dryclean_2",
      "dryclean_3",
      "dryclean_4",
      "dryclean_5",
      "dryclean_7",
    ],
  },
  {
    id: "dryclean_2",
    title: "Химчистка торпеды и стоек",
    shortDescription: "Обработка панели и стоек",
    longDescription: "Удаление загрязнений и пятен с панели и стоек",
    category: "dryclean",
    popular: false,
    resultDescriptions: ["Панель чистая и свежая", "Материалы защищены"],
    tags: ["~30 мин"],
    prices: { sedan: 1500, crossover: 1500, minivan: 1500 },
    duration: { sedan: 30, crossover: 30, minivan: 30 },
    objectTypes: ["sedan", "crossover", "minivan"],
    mainImage: "",
    additionalImages: [],
    subServiceIds: [],
    parentServiceId: "dryclean_1",
  },
  {
    id: "dryclean_3",
    title: "Химчистка одного сидения",
    shortDescription: "Чистка одного сидения",
    longDescription: "Глубокая чистка одного сидения салона",
    category: "dryclean",
    popular: false,
    resultDescriptions: ["Сидение чистое и сухое", "Удалены пятна и запахи"],
    tags: ["~20 мин"],
    prices: { sedan: 800, crossover: 800, minivan: 800 },
    duration: { sedan: 20, crossover: 20, minivan: 20 },
    objectTypes: ["sedan", "crossover", "minivan"],
    mainImage: "",
    additionalImages: [],
    subServiceIds: [],
    measure: "шт",

    parentServiceId: "dryclean_1",
  },
  {
    id: "dryclean_4",
    title: "Химчистка одной двери",
    shortDescription: "Чистка дверной панели",
    longDescription: "Глубокая очистка дверной панели и внутренней обшивки",
    category: "dryclean",
    popular: false,
    resultDescriptions: ["Дверь чистая", "Материалы обновлены"],
    tags: ["~15 мин"],
    prices: { sedan: 300, crossover: 300, minivan: 300 },
    duration: { sedan: 15, crossover: 15, minivan: 15 },
    objectTypes: ["sedan", "crossover", "minivan"],
    mainImage: "",
    additionalImages: [],
    subServiceIds: [],
    measure: "шт",
    parentServiceId: "dryclean_1",
  },
  {
    id: "dryclean_5",
    title: "Химчистка ковролина",
    shortDescription: "Чистка ковровых покрытий",
    longDescription: "Глубокая очистка ковролина в салоне и багажнике",
    category: "dryclean",
    popular: true,
    resultDescriptions: ["Ковролин чистый", "Удалены пятна и запахи"],
    tags: ["~1 ч"],
    prices: { sedan: 2500, crossover: 2500, minivan: 2500, special: 1200 },
    duration: { sedan: 60, crossover: 60, minivan: 60, special: 60 },
    objectTypes: ["sedan", "crossover", "minivan"],
    mainImage: "",
    additionalImages: [],
    subServiceIds: ["salon_2"],
    parentServiceId: "dryclean_1",
  },
  {
    id: "dryclean_6",
    title: "Химчистка багажника",
    shortDescription: "Очистка багажника",
    longDescription: "Удаление грязи и пятен из багажника",
    category: "dryclean",
    popular: false,
    resultDescriptions: ["Багажник чистый", "Удалены пятна и запахи"],
    tags: ["~45 мин"],
    prices: { sedan: 2000, crossover: 2000, minivan: 2000, special: 1200 },
    duration: { sedan: 45, crossover: 45, minivan: 45, special: 45 },
    objectTypes: ["sedan", "crossover", "minivan"],
    mainImage: "",
    additionalImages: [],
    subServiceIds: ["salon_7"],
  },
  {
    id: "dryclean_7",
    title: "Химчистка потолка",
    shortDescription: "Очистка потолочного покрытия",
    longDescription: "Удаление загрязнений и пятен с потолка салона",
    category: "dryclean",
    popular: false,
    resultDescriptions: ["Потолок чистый и свежий", "Материалы обновлены"],
    tags: ["~1 ч"],
    prices: { sedan: 2500, crossover: 2500, minivan: 2500, special: 1200 },
    duration: { sedan: 60, crossover: 60, minivan: 60, special: 60 },
    objectTypes: ["sedan", "crossover", "minivan"],
    mainImage: "",
    additionalImages: [],
    parentServiceId: "dryclean_1",
  },

  // ====== Специальные ======
  {
    id: "special_1",
    title: "Химчистка ковра",
    shortDescription: "Уникальные работы",
    longDescription: "Специальные услуги для нестандартных задач",
    category: "special",
    popular: true,
    resultDescriptions: [],
    tags: ["~120мин"],
    prices: { special: 250 },
    duration: { special: 120 },
    objectTypes: ["special"],
    mainImage: "",
    additionalImages: [],
    subServiceIds: [],
    measure: "кв.м",
    from: true,
  },
  {
    id: "special_2",
    title: "Химчистка детских кресел и колясок",
    shortDescription: "Чистка детских кресел и колясок",
    longDescription:
      "Удаление пятен и запахов с детских кресел и колясок Удаление пятен и запахов с детских кресел и колясок Удаление пятен и запахов с детских кресел и колясок Удаление пятен и запахов с детских кресел и колясок",
    category: "special",
    popular: false,
    resultDescriptions: [
      "Кресло чистое и безопасное",
      "Удалены запахи и пятна",
    ],
    tags: ["~30 мин"],
    prices: { special: 1000 },
    duration: { sedan: 30, crossover: 30, minivan: 30 },
    objectTypes: ["special"],
    mainImage: "",
    additionalImages: [],
    subServiceIds: [],
  },
];
